FROM ubuntu
WORKDIR /lv/welcome
ADD welcome.txt welcome.txt
#CMD ["cat", "welcome.txt"]
# CMD cat welcome.txt
# CMD: it also lets you to run more commands on the it mode
ENTRYPOINT ["cat", "welcome.txt"]
# ENTRYPOINT: it will run the command in the entry point and it 
# will not let you to run any other command on the it mode